url: http://avoimempi.fi
cdn: http://cdn.avoimempi.fi
secure_cdn: https://cdn.example.com.invalid

title: Avoimempi.fi
description: Avoimempi
language: fi
theme: default

style_version: dev
scripts_version: dev

author: Ville Korhonen
email: ville.korhonen@vihreat.fi

markdown: rdiscount
pygments: true
exclude:
    - README.md
    - requirements.txt

permalink: pretty
